---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  rbac.authorization.k8s.io/aggregate-to-view: "true"
  namespace: istio-system
  name: istio-view
rules:
  - apiGroups:
  - config.istio.io
  resources:
  - adapters
  - attributemanifests
  - handlers
  - httpapispecbindings
  - httpapispecs
  - instances
  - quotaspecbindings
  - quotaspecs
  - rules
  - templates
  verbs: ["get", "watch", "list"]
  - apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - sidecars
  - virtualservices
  - workloadentries
  verbs: ["get", "watch", "list"]
  - apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  - peerauthentications
  - requestauthentications
  verbs: ["get", "watch", "list"]
  
  ---
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: istio-edit
      namespace: istio-system
    subjects:
    - kind: ServiceAccount
      name: serviceaccount
      namespace: istio-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: istio-edit
